@url = http://localhost:3000
@users= {{url}}/users


###
POST {{users}}/
Content-Type: application/json
Authorization: Bearer token

{
    "dni": 123,
    "nombre" : "pepito",
    "apellido": "ricardi",
    "mail": "algunmail",
    "password": "asd123",
    "is_profe": false
}
